// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwYU_Yovy2qjsLlwQfL9iBjuc71qZkelA',
    appId: '1:1046075671423:web:4f3687de026ce0ff37904a',
    messagingSenderId: '1046075671423',
    projectId: 'fir-gallery-7a6cc',
    authDomain: 'fir-gallery-7a6cc.firebaseapp.com',
    storageBucket: 'fir-gallery-7a6cc.appspot.com',
    measurementId: 'G-VTXP8NVXQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRLMUsSf9Tjb3YBZKD-AZ3XiCTZfCZiE',
    appId: '1:1046075671423:android:044f3f8f5181f03a37904a',
    messagingSenderId: '1046075671423',
    projectId: 'fir-gallery-7a6cc',
    storageBucket: 'fir-gallery-7a6cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiH4Sm7a1so0q8KE6vx1wo94Z0n6hTPIQ',
    appId: '1:1046075671423:ios:ea0a0d81df1a3b1737904a',
    messagingSenderId: '1046075671423',
    projectId: 'fir-gallery-7a6cc',
    storageBucket: 'fir-gallery-7a6cc.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiH4Sm7a1so0q8KE6vx1wo94Z0n6hTPIQ',
    appId: '1:1046075671423:ios:58a54fbd33668f6e37904a',
    messagingSenderId: '1046075671423',
    projectId: 'fir-gallery-7a6cc',
    storageBucket: 'fir-gallery-7a6cc.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery.RunnerTests',
  );
}
