// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xOGGbvMDYnqFrCv4Cfw1v1Ukr-TTs-c',
    appId: '1:35295899385:web:f2a0fd7b6d5399845a3c28',
    messagingSenderId: '35295899385',
    projectId: 'colorfuleffects-3cac2',
    authDomain: 'colorfuleffects-3cac2.firebaseapp.com',
    storageBucket: 'colorfuleffects-3cac2.appspot.com',
    measurementId: 'G-RFEKGH0TLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ipeMDeociefenoub0rzKMyRKEzWmXgs',
    appId: '1:35295899385:android:3128230c1f762f9b5a3c28',
    messagingSenderId: '35295899385',
    projectId: 'colorfuleffects-3cac2',
    storageBucket: 'colorfuleffects-3cac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAatuRopA2fNFwgWv1IyJGCyKUZ8o9lqFg',
    appId: '1:35295899385:ios:2ce8df9e39d184585a3c28',
    messagingSenderId: '35295899385',
    projectId: 'colorfuleffects-3cac2',
    storageBucket: 'colorfuleffects-3cac2.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAatuRopA2fNFwgWv1IyJGCyKUZ8o9lqFg',
    appId: '1:35295899385:ios:701ff0da9d973aff5a3c28',
    messagingSenderId: '35295899385',
    projectId: 'colorfuleffects-3cac2',
    storageBucket: 'colorfuleffects-3cac2.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery.RunnerTests',
  );
}
